-- AlterTable
ALTER TABLE `gastos_fijos_mensual` ADD COLUMN `cuenta` ENUM('CUSCATLAN', 'MULTIMONEY', 'BAC', 'AGRICOLA_PRINCIPAL', 'AGRICOLA_SECUNDARIA') NULL,
    MODIFY `fuente` ENUM('EFECTIVO', 'TARJETA', 'CUENTA_BANCO', 'EXTERNO') NOT NULL DEFAULT 'EFECTIVO';

-- AlterTable
ALTER TABLE `transacciones` ADD COLUMN `cuenta` ENUM('CUSCATLAN', 'MULTIMONEY', 'BAC', 'AGRICOLA_PRINCIPAL', 'AGRICOLA_SECUNDARIA') NULL,
    MODIFY `fuente` ENUM('EFECTIVO', 'TARJETA', 'CUENTA_BANCO', 'EXTERNO') NOT NULL DEFAULT 'EFECTIVO';

